In [4]:
#pip install cmake

In [5]:
#pip install "C:\Users\xiexi\Downloads\dlib-19.24.1-cp311-cp311-win_amd64.whl"

In [6]:
#pip install face_recognition

In [7]:
import cv2
import os
import numpy as np
import face_recognition

In [8]:
path='images'

In [9]:
mylist=os.listdir(path)
mylist

['burak ozcivit.jpeg',
 'heath ledger.jpeg',
 'leighton meester_.jpeg',
 'ozge torer.jpeg',
 'rani mukerji.jpeg',
 'TARZZAN.jpeg']

In [10]:
imgs=[]
classname=[]
for img in mylist:
    imgpath=os.path.join(path,img)
    print(imgpath)
    current_img=cv2.imread(imgpath)
    print(current_img)
    imgs.append(current_img)
    classname.append(img[:-5])
print(len(imgs))
print(classname)

images\burak ozcivit.jpeg
[[[ 48  61 123]
  [ 56  69 131]
  [ 56  71 133]
  ...
  [ 72  88 100]
  [ 92 107 116]
  [ 97 112 121]]

 [[ 26  36  96]
  [ 45  56 116]
  [ 55  66 126]
  ...
  [149 165 177]
  [105 121 133]
  [122 137 146]]

 [[  0   0  50]
  [ 10  15  70]
  [ 28  35  90]
  ...
  [232 250 255]
  [113 129 141]
  [ 93 109 121]]

 ...

 [[ 50  14   8]
  [ 56  20  14]
  [ 54  16  11]
  ...
  [ 32  33  47]
  [ 49  50  64]
  [ 15  17  28]]

 [[ 62  28  22]
  [ 58  24  18]
  [ 50  14   8]
  ...
  [ 23  26  40]
  [ 22  25  39]
  [ 33  37  48]]

 [[ 51  17  11]
  [ 53  19  13]
  [ 57  21  15]
  ...
  [ 33  39  52]
  [ 21  24  38]
  [ 28  32  43]]]
images\heath ledger.jpeg
[[[  2   0   1]
  [  2   0   1]
  [  2   0   1]
  ...
  [  1   0   4]
  [  1   0   4]
  [  1   0   4]]

 [[  7   4   6]
  [  5   4   6]
  [  7   4   6]
  ...
  [  3   4   8]
  [  3   4   8]
  [  3   3   9]]

 [[  0   0   3]
  [  0   0   3]
  [  0   0   3]
  ...
  [  0   0   4]
  [  0   0   4]
  [  0   0   6]]

 ...

 

In [11]:
img=imgs[0]
img=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
face_in_frame=face_recognition.face_locations(img)
face_in_frame

[(202, 390, 356, 236)]

In [12]:
#pip list

In [13]:
#pip uninstall numpy

In [14]:
#pip install numpy==1.26.4